version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pwd123
      # - GF_RENDERING_SERVER_URL=http://localhost:8081/render
      # - GF_RENDERING_CALLBACK_URL=http://localhost:3000/
      # - GF_LOG_FILTERS=rendering:debug
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  # renderer:
  #   image: grafana/grafana-image-renderer:latest
  #   ports:
  #     - 8081:8081
  opa: 
    build: ./opa
    container_name: opa
    ports:
      - 8181:8181
    volumes:
      - ./opa/optimizedBundle:/opt/policies
    network_mode: host
volumes:
  prom_data: