global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: "OPAREST"
  static_configs:
  - targets: ["localhost:9080"]
- job_name: "JARL"
  static_configs:
  - targets: ["localhost:9081"]
- job_name: "WASM"
  static_configs:
  - targets: ["localhost:9082"]
- job_name: "PH"
  static_configs:
  - targets: ["localhost:9083"]
